// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_patient_ids_index from "./routes/api/patient_ids/index.ts";
import * as $api_patientsummary_patientId_ from "./routes/api/patientsummary/[patientId].ts";
import * as $index from "./routes/index.tsx";
import * as $patientsummary_patientId_index from "./routes/patientsummary/[patientId]/index.tsx";
import * as $patientsummary_index from "./routes/patientsummary/index.tsx";
import * as $PatientViewer from "./islands/PatientViewer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/patient_ids/index.ts": $api_patient_ids_index,
    "./routes/api/patientsummary/[patientId].ts":
      $api_patientsummary_patientId_,
    "./routes/index.tsx": $index,
    "./routes/patientsummary/[patientId]/index.tsx":
      $patientsummary_patientId_index,
    "./routes/patientsummary/index.tsx": $patientsummary_index,
  },
  islands: {
    "./islands/PatientViewer.tsx": $PatientViewer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
