# Main application settings
port: 3000
host: "127.0.0.1" # Sử dụng "0.0.0.0" nếu bạn muốn gateway lắng nghe trên tất cả các network interface
base_url: "http://localhost:3000" # URL cơ sở mà người dùng sẽ truy cập gateway
session_key: "a_very_long_and_secure_random_string_for_development_only_replace_this"

# Cấu hình cho nhiều OAuth2 clients
oauth_clients:
  epic_sandbox: # Tên định danh cho client này (ví dụ: "epic_sandbox")
    client_id: "45c7f20b-158f-4f1c-8746-7348814a65bd"
    client_secret: "YOUR_EPIC_CLIENT_SECRET" # Cân nhắc dùng biến môi trường APP_EPIC_SANDBOX_OAUTH_CLIENT_SECRET
    auth_url: "https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize"
    token_url: "https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token"
    # redirect_uri: "http://localhost:3000/epic-sandbox/callback" # Redirect URI cho Epic
    redirect_uri: "https://suddenly-novel-goldfish.ngrok-free.app/epic-sandbox/callback" # Redirect URI cho Epic
    scopes: [
        "openid"
      ]
    audience: "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4"
    private_key_pem: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvkY/OpAYedPP+
        HJi0j7D/w93REAM83uw8RRJLfxGqQm1zUkFKONEHONM1nL4yFSF1BdUI/czx1XLv
        4tT2Hdzneao/U6+qXwnVY6/sgykcZMKPu5xabg9oBjbPJYuHM3uTahQqvgozSWkq
        mkK/DT1Aa2LViXRCHLNDRcftQiFP4/EpVxF1Jg/vlfp9JKVUspszDd39y8BwCjjh
        k5rM9oYkxX32uP59WTvCrzwCTR7j3br2synuT6k9DbWeQW9IdTzGX0vm/aLhprDf
        pEzFgflW2r3rWOHK1qjo4LbU/iRZ5GFd/8YGHhC0HCDNVcFwITqA0PRo+V8EC6US
        KxYlt49nAgMBAAECggEAMT1tbEKjdrJNZhUGHQn51dnMoeBQUCejcMncdjEWtr43
        rTLCHftuYIym6+/ghfJYNlZi58kqzB6VxELFgJtig8cjIOyrJWjPPLpfMkGc65o0
        2RQAp3obtwybHaDFj684NuF283/mI3kw1iJ6mtOvPJyBlSseYJZlDnaJOnkkF5/6
        wbyxeBgFbCH85RR8xFiryIY7z1Dzf/O7M639jNk36sdiVR3e/NqwLJ4CccFLqsza
        5MC7sQUihTqd2tUMcBQLL1fw2u3QePxr+kitECwAiWNCy00q2+CCWP9yQ2L6qGNZ
        bPkGAh1v2RB+mm7cpPT74TbF8zT1txxJn0WqkcmVrQKBgQDfqpoeShoZAPlbe0II
        hu4KIhaYUwTPrealYcdyEvMFIXlay1XDloiSb56zuL2ECeYncT3x+C8rNqVFUeqT
        T61y5z8KLlmMvY+23bTuRrtIrE0QciCpPjj+1VAZrqRBpcqrCYLYYCDVVUatQ7dT
        IlJqaVeNzETET3y0m1GGtPwDDQKBgQDI8vdfx7a5578kC3gb1apvsUnjII+YC+sV
        NchP0v8Vy/N6eAzlqtNZXh7l5j7TIBmpb2pVtSuJVhgPZW576POkv6P0jJIvBND7
        oJWiaMiBOQKD9DBQi9g/oEmOutpa4aTuIJY1IYQBPFuS4ErFvsZFOo5lC6fXL5GV
        FUZMAKkPQwKBgF8SNDplwxwXtuZ0yQe42tvBy5rpxuTEBYMMwesyNMxcgyndvlHJ
        3blo6qt3/k5uqr7fOrZsiRg0PSHvBOei+ZYax0f7laLmPH09VhfmRttIKeWwrUNj
        KHThlQ+llTo2T6ROAakZiztC6Szi2LzknOWQa1/hkOVk6BwY3RmGOozNAoGAd3r3
        mQyPWhQwM0daf/pYH5cjXpfCqV4UxgS3eLb1Esm0mFH/ISOkDNQIvRtcqX3BpFvp
        ttJE86CsJ6NgwO4ux/tmigZ2+Nv9QlAmCG4TIbp7A2hSveGYj6RHeEUjhbv6q9fW
        V/r4mR+BN2CDNPaMvybk+bGndywCfMkshg4ydy8CgYEAmRe7QeELYtes8aCf3ni/
        t8P2uSJOgHS8Aj9RY2jyIc50I+Dv+y/jeM2odm4JuJO4ivxG0MFtuRLuaoyWxaz5
        R4/8gKWcsJmO2R78K63TYKslLXptRHTE0RdV+nFAmwitTRC6q+jhdJAC3GIOyROf
        f2ZJklshnxgrHpF0ia/Etdw=
        -----END PRIVATE KEY-----

    key_id: "sample-key-id" # Nếu Epic yêu cầu, lấy từ portal hoặc để trống nếu không có
    jwt_algorithm: "RS384"  # Epic khuyến nghị dùng RS384 với key mẫu này
  google: # Tên định danh cho client Google
    client_id: "YOUR_GOOGLE_CLIENT_ID" # Cân nhắc dùng biến môi trường APP_GOOGLE_OAUTH_CLIENT_ID
    client_secret: "YOUR_GOOGLE_CLIENT_SECRET" # Cân nhắc dùng biến môi trường APP_GOOGLE_OAUTH_CLIENT_SECRET
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
    token_url: "https://oauth2.googleapis.com/token"
    redirect_uri: "http://localhost:3000/google/callback" # Redirect URI cho Google
    # Google thường không dùng private_key_jwt cho web server flows, nên các trường private_key_* có thể là None/null
    private_key_pem: null
    private_key_algorithm: null
    key_id: null
    scopes: [
        "openid"
      ]
    audience: "YOUR_GOOGLE_CLIENT_ID" # Audience cho Google thường là client_id

  # Thêm các nhà cung cấp OAuth2 khác ở đây
  # another_provider:
  #   client_id: "..."
  #   ...
